import './globals.css'

import { NextUIProvider } from '@nextui-org/react'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import React from 'react'

const inter = Inter({ subsets: ['vietnamese'], variable: '--font-inter' })
const roboto = Roboto({
  subsets: ['vietnamese'],
  variable: '--font-roboto',
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
  params: {
    locale: string
  }
}
export default async function RootLayout({
  children,
}: Readonly<RootLayoutProps>) {
  return (
    <html
      lang='vi'
      data-theme='light'
      className={`${inter.variable} ${roboto.variable}`}
    >
      <body className={inter.className}>
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  )
}
